apiVersion: v1
kind: Service
metadata:
  name: ebpf-edge-agent
  namespace: observability
  labels:
    app: ebpf-edge-agent
    component: telemetry
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for DaemonSet
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ebpf-edge-agent
---
apiVersion: v1
kind: Service
metadata:
  name: ebpf-edge-agent-nodeport
  namespace: observability
  labels:
    app: ebpf-edge-agent
    component: telemetry
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    app: ebpf-edge-agent
